import 'dart:convert';
import 'dart:typed_data';

import '../models/artifact.dart';
import '../models/conversation.dart';

const _imageKeywords = [
  'image', 'photo', 'picture', 'logo', 'graphic', 'illustration',
  'banner', 'thumbnail', 'icon',
];

const _artifactReferenceKeywords = [
  'to the website', 'to the page', 'to the site', 'to my website',
  'to my page', 'to my site', 'on the website', 'on the page',
  'on the site', 'for the website', 'for the page', 'for the site',
  'to it', 'on it', 'hero image', 'hero section', 'header image',
  'background image', 'to this page', 'on this page', 'to the artifact',
];

/// The most recent HTML artifact in the conversation, if any — the only
/// kind of artifact an image can be visually spliced into.
Artifact? latestHtmlArtifact(Conversation conversation) {
  for (final artifact in conversation.artifacts.reversed) {
    if (artifact.kind == ArtifactKind.html) return artifact;
  }
  return null;
}

/// Detects "add a hero image to the website" style requests: a visual asset
/// meant to be woven into an artifact that already exists, rather than a
/// standalone image. This is how two studios compose within a single turn —
/// Image Studio generates the asset, then it's spliced into Code Studio's
/// output — without the user managing that handoff themselves.
Artifact? findArtifactCompositionTarget(
  Conversation conversation,
  String userInput,
) {
  final target = latestHtmlArtifact(conversation);
  if (target == null) return null;
  final lower = userInput.toLowerCase();
  final mentionsImage = _imageKeywords.any(lower.contains);
  final mentionsArtifact = _artifactReferenceKeywords.any(lower.contains);
  if (!mentionsImage || !mentionsArtifact) return null;
  return target;
}

/// Splices a generated image into an HTML artifact as a base64 data URI,
/// right at the top of `<body>` — the "hero" position. Pure string surgery,
/// so it behaves identically for mock-rasterized and live-generated bytes.
String embedImageAsHero(
  String html,
  Uint8List pngBytes, {
  String altText = 'Generated image',
}) {
  final dataUri = 'data:image/png;base64,${base64Encode(pngBytes)}';
  final safeAlt = altText.replaceAll('"', "'");
  final imgTag = '<img src="$dataUri" alt="$safeAlt" '
      'style="max-width:100%;height:auto;display:block;margin:0 auto 24px;" />';
  final bodyMatch =
      RegExp(r'<body[^>]*>', caseSensitive: false).firstMatch(html);
  if (bodyMatch == null) {
    return '$imgTag\n$html';
  }
  final insertAt = bodyMatch.end;
  return '${html.substring(0, insertAt)}\n$imgTag${html.substring(insertAt)}';
}

/// Whether the prompt reads as referring to an artifact that already exists
/// ("add a hero image **to the website**"), as opposed to describing a fresh
/// build. Used to keep the edit path and the fresh page-assembly path
/// mutually exclusive on the same "website" + "image" wording.
bool referencesExistingArtifact(String input) {
  final lower = input.toLowerCase();
  return _artifactReferenceKeywords.any(lower.contains);
}

/// How many images a combined build request wants: an explicit count
/// ("3 photos") wins; vague plurals ("several", "photos") default to a
/// small gallery; a singular mention ("a logo") wants just one.
int photoCountHint(String input) {
  final lower = input.toLowerCase();
  final numMatch = RegExp(r'\b(\d+)\s*(photos?|images?|pictures?|logos?)\b')
      .firstMatch(lower);
  if (numMatch != null) {
    return int.parse(numMatch.group(1)!).clamp(1, 6);
  }
  if (RegExp(r'\b(several|multiple|many)\b').hasMatch(lower)) return 3;
  if (RegExp(r'\b(a few|couple)\b').hasMatch(lower)) return 2;
  if (RegExp(r'\b(photos|images|pictures|logos)\b').hasMatch(lower)) return 3;
  return 1;
}

/// Splices multiple generated images into an HTML artifact as a simple
/// responsive gallery grid, right after the opening `<body>` tag — the
/// multi-image counterpart to [embedImageAsHero] (which this delegates to
/// for a single image, so both share one insertion point).
String embedImageGallery(
  String html,
  List<Uint8List> images, {
  String altText = 'Generated image',
}) {
  if (images.length == 1) {
    return embedImageAsHero(html, images.single, altText: altText);
  }
  final safeAlt = altText.replaceAll('"', "'");
  final tiles = images
      .map((bytes) =>
          '<img src="data:image/png;base64,${base64Encode(bytes)}" '
          'alt="$safeAlt" style="width:100%;aspect-ratio:1;object-fit:cover;'
          'border-radius:12px;" />')
      .join();
  final galleryHtml = '<div style="display:grid;'
      'grid-template-columns:repeat(auto-fit, minmax(180px, 1fr));'
      'gap:16px;max-width:960px;margin:0 auto 24px;padding:0 24px;">'
      '$tiles</div>';
  final bodyMatch =
      RegExp(r'<body[^>]*>', caseSensitive: false).firstMatch(html);
  if (bodyMatch == null) return '$galleryHtml\n$html';
  final insertAt = bodyMatch.end;
  return '${html.substring(0, insertAt)}\n$galleryHtml${html.substring(insertAt)}';
}
