import 'dart:convert';
import 'dart:typed_data';

import '../models/artifact.dart';
import '../models/conversation.dart';

const _imageKeywords = [
  'image', 'photo', 'picture', 'logo', 'graphic', 'illustration',
  'banner', 'thumbnail', 'icon',
];

const _artifactReferenceKeywords = [
  'to the website', 'to the page', 'to the site', 'to my website',
  'to my page', 'to my site', 'on the website', 'on the page',
  'on the site', 'for the website', 'for the page', 'for the site',
  'to it', 'on it', 'hero image', 'hero section', 'header image',
  'background image', 'to this page', 'on this page', 'to the artifact',
];

/// The most recent HTML artifact in the conversation, if any — the only
/// kind of artifact an image can be visually spliced into.
Artifact? latestHtmlArtifact(Conversation conversation) {
  for (final artifact in conversation.artifacts.reversed) {
    if (artifact.kind == ArtifactKind.html) return artifact;
  }
  return null;
}

/// Detects "add a hero image to the website" style requests: a visual asset
/// meant to be woven into an artifact that already exists, rather than a
/// standalone image. This is how two studios compose within a single turn —
/// Image Studio generates the asset, then it's spliced into Code Studio's
/// output — without the user managing that handoff themselves.
Artifact? findArtifactCompositionTarget(
  Conversation conversation,
  String userInput,
) {
  final target = latestHtmlArtifact(conversation);
  if (target == null) return null;
  final lower = userInput.toLowerCase();
  final mentionsImage = _imageKeywords.any(lower.contains);
  final mentionsArtifact = _artifactReferenceKeywords.any(lower.contains);
  if (!mentionsImage || !mentionsArtifact) return null;
  return target;
}

/// Splices a generated image into an HTML artifact as a base64 data URI,
/// right at the top of `<body>` — the "hero" position. Pure string surgery,
/// so it behaves identically for mock-rasterized and live-generated bytes.
String embedImageAsHero(
  String html,
  Uint8List pngBytes, {
  String altText = 'Generated image',
}) {
  final dataUri = 'data:image/png;base64,${base64Encode(pngBytes)}';
  final safeAlt = altText.replaceAll('"', "'");
  final imgTag = '<img src="$dataUri" alt="$safeAlt" '
      'style="max-width:100%;height:auto;display:block;margin:0 auto 24px;" />';
  final bodyMatch =
      RegExp(r'<body[^>]*>', caseSensitive: false).firstMatch(html);
  if (bodyMatch == null) {
    return '$imgTag\n$html';
  }
  final insertAt = bodyMatch.end;
  return '${html.substring(0, insertAt)}\n$imgTag${html.substring(insertAt)}';
}
