import 'dart:io';
import 'dart:typed_data';

/// Off-web: one file per asset, beside the settings this app already keeps.
///
/// A directory of files rather than one container, because that is the only
/// shape where reading one image does not mean reading all of them — which is
/// the whole reason bytes left [KvStore] in the first place.
class AssetStore {
  final String _directory;

  AssetStore({String? directory})
      : _directory = directory ??
            '${Platform.environment['HOME'] ?? '.'}/.shift/assets';

  /// Rejects anything that could name a file outside the directory.
  ///
  /// Ids are generated by this app and so are safe today, but this is the one
  /// place a hostile or merely wrong id becomes a write to an arbitrary path,
  /// and the check costs nothing. A rejected id is treated as absent, not as
  /// an error: the caller's job is to show a missing image, not to crash.
  bool _safe(String id) =>
      id.isNotEmpty &&
      !id.contains('/') &&
      !id.contains(r'\') &&
      !id.contains('..');

  File _file(String id) => File('$_directory/$id');

  Future<void> put(String id, Uint8List bytes) async {
    if (!_safe(id)) return;
    final file = _file(id);
    await file.parent.create(recursive: true);
    await file.writeAsBytes(bytes, flush: true);
  }

  Future<Uint8List?> get(String id) async {
    if (!_safe(id)) return null;
    try {
      return await _file(id).readAsBytes();
    } catch (_) {
      // Absent or unreadable are the same fact to a caller: there is no image
      // to show. Distinguishing them would offer a remedy that does not exist.
      return null;
    }
  }

  Future<void> remove(String id) async {
    if (!_safe(id)) return;
    try {
      await _file(id).delete();
    } catch (_) {
      // Already gone is the outcome that was asked for.
    }
  }

  /// Every asset this store holds. Used to erase them and to find bytes no
  /// index points at any more.
  Future<List<String>> ids() async {
    try {
      final entries = await Directory(_directory).list().toList();
      return [
        for (final entry in entries)
          if (entry is File) entry.uri.pathSegments.last,
      ];
    } catch (_) {
      return const [];
    }
  }

  Future<void> clear() async {
    for (final id in await ids()) {
      await remove(id);
    }
  }
}
