import 'package:flutter_test/flutter_test.dart';
import 'package:shift_ai/data/models/artifact.dart';
import 'package:shift_ai/data/models/conversation.dart';
import 'package:shift_ai/data/models/studio_type.dart';
import 'package:shift_ai/turn/chat_service.dart';
import 'package:shift_ai/turn/backends/mock_backend.dart';

Conversation _empty() => Conversation(
      id: 'c1',
      title: 'Test',
      createdAt: DateTime(2026, 7, 20),
      updatedAt: DateTime(2026, 7, 20),
    );

Future<Artifact> _buildPage(String prompt) async {
  final events =
      await MockChatService().sendMessage(conversation: _empty(), userInput: prompt).toList();
  return events.whereType<ArtifactCreated>().single.artifact;
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test('contributors still run when the conversation has a code artifact',
      () async {
    // The mock used to revise whatever artifact was last and return before
    // page assembly ever ran, so a multi-studio build silently degraded to a
    // content-free revision. (Only reachable via a code artifact: a page
    // request is not planned as an assembly once an HTML artifact exists.)
    final existing = Artifact(
      id: 'code1',
      conversationId: 'c1',
      title: 'parse_dates.py',
      kind: ArtifactKind.code,
      versions: [
        ArtifactVersion(content: 'print(1)', createdAt: DateTime(2026, 7, 20)),
      ],
    );
    final conversation = Conversation(
      id: 'c1',
      title: 'Test',
      createdAt: DateTime(2026, 7, 20),
      updatedAt: DateTime(2026, 7, 20),
      artifacts: [existing],
    );
    final events = await MockChatService()
        .sendMessage(
          conversation: conversation,
          userInput: 'build me a bakery website with a soundtrack',
          options: ChatOptions.none,
        )
        .toList();

    expect(events.whereType<ArtifactUpdated>(), isEmpty);
    final artifact = events.whereType<ArtifactCreated>().single.artifact;
    expect(artifact.kind, ArtifactKind.html);
    expect(artifact.latest.content, contains('<audio controls'));
  }, timeout: const Timeout(Duration(minutes: 2)));

  test('a website with a soundtrack embeds a playable audio player',
      () async {
    final artifact =
        await _buildPage('build me a bakery website with a soundtrack');
    expect(artifact.kind, ArtifactKind.html);
    expect(artifact.latest.content, contains('<audio controls'));
    expect(artifact.latest.content, contains('data:audio/wav;base64,'));
    expect(artifact.latest.content, contains('Soundtrack'));
  }, timeout: const Timeout(Duration(minutes: 2)));

  test('a website with a headline embeds real copy in the hero', () async {
    final artifact =
        await _buildPage('build me a bakery website with a headline');
    // The placeholder hero copy is replaced.
    expect(
      artifact.latest.content.contains("Generated by SHIFT AI's Code Studio"),
      isFalse,
    );
  }, timeout: const Timeout(Duration(minutes: 2)));

  test('a website with a video clip embeds a simulated-video block',
      () async {
    final artifact =
        await _buildPage('build me a bakery website with a video clip');
    expect(artifact.latest.content, contains('Simulated video'));
  }, timeout: const Timeout(Duration(minutes: 2)));

  test('a website with photos, a soundtrack and copy assembles all three '
      'into one artifact version', () async {
    final events = await MockChatService()
        .sendMessage(
          conversation: _empty(),
          userInput: 'build me a dog treat website with several photos, '
              'a soundtrack and a headline',
        )
        .toList();

    expect(events.whereType<RoutingDetected>().single.studioType,
        StudioType.codeStudio);
    final artifact = events.whereType<ArtifactCreated>().single.artifact;
    expect(artifact.versions, hasLength(1));
    expect('<img'.allMatches(artifact.latest.content).length, 3);
    expect(artifact.latest.content, contains('<audio controls'));
    expect(
      artifact.latest.content.contains("Generated by SHIFT AI's Code Studio"),
      isFalse,
    );

    // Routing is invisible (like Claude): the visible text names no studios.
    final text = events.whereType<MessageDelta>().map((e) => e.chunk).join();
    expect(text, isNot(contains('Studio')));

    // Woven into the page, not shown as separate cards.
    expect(events.whereType<StudioResultReady>(), isEmpty);
  }, timeout: const Timeout(Duration(minutes: 2)));

  test('a plain page (no contributor keyword) has no embedded media',
      () async {
    final artifact = await _buildPage('build me a landing page for my bakery');
    expect(artifact.latest.content.contains('<img'), isFalse);
    expect(artifact.latest.content.contains('<audio'), isFalse);
    expect(artifact.latest.content.contains('Simulated video'), isFalse);
  }, timeout: const Timeout(Duration(minutes: 2)));
}
