import 'package:flutter_test/flutter_test.dart';
import 'package:shift_ai/models/artifact.dart';
import 'package:shift_ai/models/conversation.dart';
import 'package:shift_ai/models/studio_type.dart';
import 'package:shift_ai/services/chat_service.dart';
import 'package:shift_ai/services/mock_chat_service.dart';

Conversation _empty() => Conversation(
      id: 'c1',
      title: 'Test',
      createdAt: DateTime(2026, 7, 20),
      updatedAt: DateTime(2026, 7, 20),
    );

Future<Artifact> _buildPage(String prompt) async {
  final events =
      await MockChatService().sendMessage(conversation: _empty(), userInput: prompt).toList();
  return events.whereType<ArtifactCreated>().single.artifact;
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test('a website with a soundtrack embeds a playable audio player',
      () async {
    final artifact =
        await _buildPage('build me a bakery website with a soundtrack');
    expect(artifact.kind, ArtifactKind.html);
    expect(artifact.latest.content, contains('<audio controls'));
    expect(artifact.latest.content, contains('data:audio/wav;base64,'));
    expect(artifact.latest.content, contains('Soundtrack'));
  }, timeout: const Timeout(Duration(minutes: 2)));

  test('a website with a headline embeds real copy in the hero', () async {
    final artifact =
        await _buildPage('build me a bakery website with a headline');
    // The placeholder hero copy is replaced.
    expect(
      artifact.latest.content.contains("Generated by SHIFT AI's Code Studio"),
      isFalse,
    );
  }, timeout: const Timeout(Duration(minutes: 2)));

  test('a website with a video clip embeds a simulated-video block',
      () async {
    final artifact =
        await _buildPage('build me a bakery website with a video clip');
    expect(artifact.latest.content, contains('Simulated video'));
  }, timeout: const Timeout(Duration(minutes: 2)));

  test('a website with photos, a soundtrack and copy assembles all three '
      'into one artifact version', () async {
    final events = await MockChatService()
        .sendMessage(
          conversation: _empty(),
          userInput: 'build me a dog treat website with several photos, '
              'a soundtrack and a headline',
        )
        .toList();

    expect(events.whereType<RoutingDetected>().single.studioType,
        StudioType.codeStudio);
    final artifact = events.whereType<ArtifactCreated>().single.artifact;
    expect(artifact.versions, hasLength(1));
    expect('<img'.allMatches(artifact.latest.content).length, 3);
    expect(artifact.latest.content, contains('<audio controls'));
    expect(
      artifact.latest.content.contains("Generated by SHIFT AI's Code Studio"),
      isFalse,
    );

    // The intro names all the collaborating studios.
    final text = events.whereType<MessageDelta>().map((e) => e.chunk).join();
    expect(text, contains('Code Studio'));
    expect(text, contains('Image Studio'));
    expect(text, contains('Music Studio'));
    expect(text, contains('Copy & Scripts Studio'));

    // Woven into the page, not shown as separate cards.
    expect(events.whereType<StudioResultReady>(), isEmpty);
  }, timeout: const Timeout(Duration(minutes: 2)));

  test('a plain page (no contributor keyword) has no embedded media',
      () async {
    final artifact = await _buildPage('build me a landing page for my bakery');
    expect(artifact.latest.content.contains('<img'), isFalse);
    expect(artifact.latest.content.contains('<audio'), isFalse);
    expect(artifact.latest.content.contains('Simulated video'), isFalse);
  }, timeout: const Timeout(Duration(minutes: 2)));
}
