


/// Pure helpers for the Brand Pack studio: derive a deterministic palette and
/// type pairing from the brand name, render brand guidelines, and zip the kit
/// (logo + palette + guidelines + tokens) into a real downloadable .zip.
import '../../../data/models/studio_result.dart';
import 'dart:convert';
import 'dart:typed_data';
import 'package:archive/archive.dart';

class BrandPackService {
  BrandPackService._();

  /// The brand name pulled from a free-form request.
  static String parseBrandName(String input) {
    var s = input
        .replaceFirst(
            RegExp(
                r'^\s*(please\s+)?(can|could|would)?\s*(you\s+)?(please\s+)?'
                r'(make|build|create|generate|design|put together)?\s*(me\s+)?'
                r'(a|an|the)?\s*(brand\s*(pack|kit|bundle|identity|book)|'
                r'logo\s*pack|style\s*guide|brand\s*guidelines|brand\s*assets)\s*',
                caseSensitive: false),
            '')
        .replaceFirst(
            RegExp(r'^\s*(for|about|called|named)\s+', caseSensitive: false),
            '')
        .trim();
    if (s.isEmpty) s = 'Your Brand';
    // Keep it to a short name.
    final words = s.split(RegExp(r'\s+')).take(4).join(' ');
    return words;
  }

  static int seedFor(String name) => name.codeUnits.fold<int>(
        7,
        (acc, c) => (acc * 31 + c) & 0x7fffffff,
      );

  /// Five deterministic, on-brand hex colours: a primary hue, two harmonious
  /// hues, a near-black ink and an off-white paper.
  static List<String> buildPalette(int seed) {
    final baseHue = seed % 360;
    return [
      _hslHex(baseHue, 0.68, 0.52), // primary
      _hslHex((baseHue + 32) % 360, 0.62, 0.58), // secondary
      _hslHex((baseHue + 210) % 360, 0.55, 0.55), // accent (complementary-ish)
      '#1D1D1F', // ink
      '#F5F4EF', // paper
    ];
  }

  static const _headingFonts = ['Georgia', 'Playfair Display', 'Fraunces', 'Times New Roman'];
  static const _bodyFonts = ['Inter', 'Helvetica Neue', 'system-ui', 'Arial'];

  static ({String heading, String body}) fontPair(int seed) => (
        heading: _headingFonts[seed % _headingFonts.length],
        body: _bodyFonts[(seed ~/ 7) % _bodyFonts.length],
      );

  /// A short brand guidelines document (Markdown).
  static String guidelinesMarkdown(BrandPackResult pack) {
    final colors = pack.palette
        .asMap()
        .entries
        .map((e) => '- ${_paletteRole(e.key)}: `${e.value}`')
        .join('\n');
    return '# ${pack.brandName} — Brand Guidelines\n\n'
        'Generated by SHIFT AI.\n\n'
        '## Logo\n\nSee `logo.png`. Keep clear space around it equal to the '
        'height of the mark. Do not stretch, recolour, or add effects.\n\n'
        '## Colour palette\n\n$colors\n\nSee `colors.css` for tokens.\n\n'
        '## Typography\n\n- Headings: **${pack.headingFont}**\n'
        '- Body: **${pack.bodyFont}**\n\n'
        '## Voice\n\nConfident, warm, and plain-spoken. Short sentences. '
        'Say what you mean.\n';
  }

  /// CSS custom properties for the palette + fonts.
  static String colorsCss(BrandPackResult pack) {
    final vars = pack.palette
        .asMap()
        .entries
        .map((e) => '  --brand-${_paletteRole(e.key)}: ${e.value};')
        .join('\n');
    return ':root {\n$vars\n'
        '  --brand-heading-font: "${pack.headingFont}", serif;\n'
        '  --brand-body-font: "${pack.bodyFont}", sans-serif;\n}\n';
  }

  /// Packages the kit into a real .zip: logo.png, colors.css, guidelines.md,
  /// palette.json.
  static Uint8List buildZip(BrandPackResult pack, Uint8List logoPng) {
    final archive = Archive();
    void addText(String path, String text) {
      final bytes = utf8.encode(text);
      archive.addFile(ArchiveFile(path, bytes.length, bytes));
    }

    final folder = _slug(pack.brandName);
    archive.addFile(ArchiveFile('$folder/logo.png', logoPng.length, logoPng));
    addText('$folder/colors.css', colorsCss(pack));
    addText('$folder/guidelines.md', guidelinesMarkdown(pack));
    addText(
        '$folder/palette.json',
        const JsonEncoder.withIndent('  ').convert({
          'brand': pack.brandName,
          'palette': pack.palette,
          'headingFont': pack.headingFont,
          'bodyFont': pack.bodyFont,
        }));

    final zip = ZipEncoder().encode(archive) ?? const <int>[];
    return Uint8List.fromList(zip);
  }

  static String _paletteRole(int i) => switch (i) {
        0 => 'primary',
        1 => 'secondary',
        2 => 'accent',
        3 => 'ink',
        _ => 'paper',
      };

  static String _slug(String s) {
    final words = s
        .toLowerCase()
        .replaceAll(RegExp(r'[^a-z0-9\s]'), '')
        .split(RegExp(r'\s+'))
        .where((w) => w.isNotEmpty)
        .take(4);
    final joined = words.join('-');
    return joined.isEmpty ? 'brand' : joined;
  }

  static String _hslHex(int h, double s, double l) {
    final c = (1 - (2 * l - 1).abs()) * s;
    final x = c * (1 - (((h / 60) % 2) - 1).abs());
    final m = l - c / 2;
    double r = 0, g = 0, b = 0;
    if (h < 60) {
      r = c; g = x;
    } else if (h < 120) {
      r = x; g = c;
    } else if (h < 180) {
      g = c; b = x;
    } else if (h < 240) {
      g = x; b = c;
    } else if (h < 300) {
      r = x; b = c;
    } else {
      r = c; b = x;
    }
    final ri = ((r + m) * 255).round().clamp(0, 255);
    final gi = ((g + m) * 255).round().clamp(0, 255);
    final bi = ((b + m) * 255).round().clamp(0, 255);
    String hex(int v) => v.toRadixString(16).padLeft(2, '0');
    return '#${hex(ri)}${hex(gi)}${hex(bi)}'.toUpperCase();
  }
}
