#!/usr/bin/env python3
"""Inline a function's `_shared` imports into one file.

The CI job in `.github/workflows/backend.yml` is how these deploy, and it is
the path that survives the next edit. This is the fallback for when it cannot
run: the Supabase dashboard's editor takes a paste, and `provider-proxy` is
five files. Pasting five files from a phone is not something to ask of anyone.

    python3 tool/bundle_function.py provider-proxy

Writes `build/functions/<name>.js`. Deliberately dumb — it resolves relative
imports of `../_shared/*.js`, strips their `export` keywords, and concatenates
in dependency order. It is not a bundler and should not become one: the moment
these functions need real bundling, they need a real build step, and this
script existing would only delay noticing.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
FUNCTIONS = ROOT / 'supabase' / 'functions'
OUT = ROOT / 'build' / 'functions'

IMPORT = re.compile(
    r"^import\s*\{([^}]*)\}\s*from\s*'(\.\./_shared/[\w.]+)';\s*$",
    re.MULTILINE,
)


def shared_source(path: pathlib.Path, seen: set) -> str:
    """The text of a `_shared` module, with its own imports resolved first."""
    if path in seen:
        return ''
    seen.add(path)

    text = path.read_text()
    prefix = ''
    for match in IMPORT.finditer(text):
        prefix += shared_source((FUNCTIONS / match.group(2)[3:]).resolve(), seen)

    body = IMPORT.sub('', text)
    # `export` means nothing once everything is in one scope, and leaving it
    # in is a syntax error outside a module.
    body = re.sub(r'^export\s+(?=(async\s+)?(function|const|class|let))', '',
                  body, flags=re.MULTILINE)
    return f'{prefix}\n// ---- {path.name} ----\n{body}\n'


def bundle(name: str) -> pathlib.Path:
    entry = FUNCTIONS / name / 'index.js'
    if not entry.exists():
        raise SystemExit(f'No such function: {name}')

    text = entry.read_text()
    seen: set = set()
    shared = ''
    for match in IMPORT.finditer(text):
        shared += shared_source((FUNCTIONS / match.group(2)[3:]).resolve(), seen)

    body = IMPORT.sub('', text)
    body = re.sub(r'^export\s+(?=(async\s+)?(function|const|class|let))', '',
                  body, flags=re.MULTILINE)
    # The default export is what the platform serves, so it stays.
    body = body.replace('export default', 'export default')

    OUT.mkdir(parents=True, exist_ok=True)
    out = OUT / f'{name}.js'
    out.write_text(
        f'// Generated by tool/bundle_function.py from '
        f'supabase/functions/{name}/ — do not edit.\n'
        f'// Paste into the Supabase dashboard only when CI cannot deploy; the\n'
        f'// workflow is the path that survives the next change.\n'
        f'{shared}\n// ---- {name}/index.js ----\n{body}\n'
    )
    return out


if __name__ == '__main__':
    if len(sys.argv) != 2:
        raise SystemExit('usage: bundle_function.py <function-name>')
    print(bundle(sys.argv[1]).relative_to(ROOT))
