import 'dart:convert';
import 'dart:typed_data';

import '../../data/models/artifact.dart';
import '../../data/models/conversation.dart';

const _imageKeywords = [
  'image', 'photo', 'picture', 'logo', 'graphic', 'illustration',
  'banner', 'thumbnail', 'icon',
];

const _audioKeywords = [
  'music', 'soundtrack', 'song', 'audio', 'sound', 'jingle', 'voiceover',
  'voice-over', 'voice over', 'narration', 'track', 'theme song',
  'background music', 'audio bed',
];

const _videoKeywords = [
  'video', 'clip', 'reel', 'footage', 'animation', 'trailer', 'movie',
];

/// The kind of media an artifact-edit request wants woven into the page.
enum ArtifactMediaKind { image, audio, video }

/// An "add X to the website" request: the artifact to splice into, and which
/// kind of media block to embed.
class ArtifactEdit {
  final Artifact target;
  final ArtifactMediaKind kind;
  const ArtifactEdit(this.target, this.kind);
}

const _artifactReferenceKeywords = [
  'to the website', 'to the page', 'to the site', 'to my website',
  'to my page', 'to my site', 'on the website', 'on the page',
  'on the site', 'for the website', 'for the page', 'for the site',
  // "put it *in* the website" is how people actually say this, and it was
  // missing — so the phrase read as a fresh build and quietly started over.
  'in the website', 'in the page', 'in the site', 'in my website',
  'in my page', 'in my site', 'in this page', 'into the website',
  'into the page', 'into the site',
  'to it', 'on it', 'hero image', 'hero section', 'header image',
  'background image', 'to this page', 'on this page', 'to the artifact',
];

/// The most recent HTML artifact in the conversation, if any — the only
/// kind of artifact an image can be visually spliced into.
Artifact? latestHtmlArtifact(Conversation conversation) {
  for (final artifact in conversation.artifacts.reversed) {
    if (artifact.kind == ArtifactKind.html) return artifact;
  }
  return null;
}

/// Detects "add a hero image to the website" style requests: a visual asset
/// meant to be woven into an artifact that already exists, rather than a
/// standalone image. This is how two studios compose within a single turn —
/// Image Studio generates the asset, then it's spliced into Code Studio's
/// output — without the user managing that handoff themselves.
ArtifactEdit? findArtifactEdit(
  Conversation conversation,
  String userInput,
) {
  final target = latestHtmlArtifact(conversation);
  if (target == null) return null;
  final lower = userInput.toLowerCase();
  if (!_artifactReferenceKeywords.any(lower.contains)) return null;
  // Priority image -> video -> audio, so "add a hero image" stays an image
  // edit even if it also mentions, say, a "background".
  if (_imageKeywords.any(lower.contains)) {
    return ArtifactEdit(target, ArtifactMediaKind.image);
  }
  if (_videoKeywords.any(lower.contains)) {
    return ArtifactEdit(target, ArtifactMediaKind.video);
  }
  if (_audioKeywords.any(lower.contains)) {
    return ArtifactEdit(target, ArtifactMediaKind.audio);
  }
  return null;
}

/// Image-only view of [findArtifactEdit], kept for callers/tests that only
/// care about the "splice an image into the page" case.
Artifact? findArtifactCompositionTarget(
  Conversation conversation,
  String userInput,
) {
  final edit = findArtifactEdit(conversation, userInput);
  return (edit != null && edit.kind == ArtifactMediaKind.image)
      ? edit.target
      : null;
}

/// Splices a generated image into an HTML artifact as a base64 data URI,
/// right at the top of `<body>` — the "hero" position. Pure string surgery,
/// so it behaves identically for mock-rasterized and live-generated bytes.
String embedImageAsHero(
  String html,
  Uint8List pngBytes, {
  String altText = 'Generated image',
}) {
  final dataUri = 'data:image/png;base64,${base64Encode(pngBytes)}';
  final safeAlt = altText.replaceAll('"', "'");
  final imgTag = '<img src="$dataUri" alt="$safeAlt" '
      'style="max-width:100%;height:auto;display:block;margin:0 auto 24px;" />';
  final bodyMatch =
      RegExp(r'<body[^>]*>', caseSensitive: false).firstMatch(html);
  if (bodyMatch == null) {
    return '$imgTag\n$html';
  }
  final insertAt = bodyMatch.end;
  return '${html.substring(0, insertAt)}\n$imgTag${html.substring(insertAt)}';
}

/// The token a code turn is told to put in an `<img src>` when the page it is
/// writing should carry an image the conversation already produced.
///
/// The model cannot see that image — a generated picture is a block in the
/// transcript, not something sent back up with the next request — so left to
/// itself it invents a plausible filename and tells the user to save the file
/// beside the page. Nobody has that file, and there is no "beside the page".
/// A placeholder lets the model *place* the image while the app supplies it.
const String generatedImagePlaceholder = '{{shift:image}}';

/// The same, for a voiceover or a score. A model told nothing writes a page
/// that reads the script with the browser's speech engine — which is not the
/// voice the user just generated.
const String generatedAudioPlaceholder = '{{shift:audio}}';

/// Puts [pngBytes] into [source]: at the placeholder the model was asked to
/// leave, or — when it left none — at the top of the body.
///
/// The fallback is what makes this reliable rather than merely likely. A model
/// that ignores the instruction still ends up with the image on the page,
/// which is the whole point of doing this in the app instead of the prompt.
///
/// It only applies to HTML, though: a React component has no `<body>` to
/// insert into, and splicing a tag into JSX by string surgery would produce
/// something that does not compile. There the placeholder is the only route,
/// which is why substituting it has to work for every artifact kind.
String applyGeneratedImage(
  String source,
  Uint8List pngBytes, {
  String altText = 'Generated image',
}) {
  final dataUri = 'data:image/png;base64,${base64Encode(pngBytes)}';
  if (source.contains(generatedImagePlaceholder)) {
    return source.replaceAll(generatedImagePlaceholder, dataUri);
  }
  if (!RegExp(r'<body[^>]*>', caseSensitive: false).hasMatch(source)) {
    return source;
  }
  return embedImageAsHero(source, pngBytes, altText: altText);
}

/// Whether the prompt reads as referring to an artifact that already exists
/// ("add a hero image **to the website**"), as opposed to describing a fresh
/// build. Used to keep the edit path and the fresh page-assembly path
/// mutually exclusive on the same "website" + "image" wording.
bool referencesExistingArtifact(String input) {
  final lower = input.toLowerCase();
  return _artifactReferenceKeywords.any(lower.contains);
}

/// An explicit request to build something new, carrying its own subject:
/// "build me a pricing page", "create a dashboard". The noun is required so
/// that "make it bigger" — which also starts with a build verb — does not
/// read as a fresh build.
final _freshBuildSignal = RegExp(
    r'\b(build|create|generate|design|make me|write me|give me)\b[\s\S]*'
    r'\b(page|site|website|app|landing|dashboard|form|game|portfolio|'
    r'blog|store|shop|calculator)\b');

/// A request to change what is already there rather than start over.
final _revisionSignal = RegExp(
    r'\b(change|changes|update|updates|fix|fixes|tweak|adjust|revise|edit|'
    r'rename|remove|delete|replace|swap|instead|refactor|simplify|'
    r'make it|make the|can you make|turn it|turn the)\b');

/// The artifact a code-routed turn should revise, or null when the turn should
/// create a fresh one.
///
/// This is the create-vs-revise decision, kept pure and shared so demo mode and
/// live mode cannot disagree about it — they used to, in opposite directions:
/// the mock revised whatever artifact happened to be last (silently overwriting
/// a page when the user asked for a different one), while the live path always
/// created, so a genuine "change the button to red" spawned a second artifact
/// instead of a version.
///
/// Distinct from [findArtifactEdit], which handles "add a hero image **to the
/// website**" — splicing generated media into a page. This decides whether the
/// *code* output replaces an existing artifact.
///
/// Ambiguity resolves to create (null). A spurious extra artifact is a nuisance
/// the user can delete; overwriting the page they asked for destroys work.
Artifact? findRevisionTarget(Conversation conversation, String userInput) {
  // Interactive artifacts (recipe cards, quizzes) live in the same list but are
  // generated wholesale from a prompt — a later code request is never a
  // revision of one.
  Artifact? candidate;
  for (final artifact in conversation.artifacts.reversed) {
    if (artifact.interactive) continue;
    if (artifact.kind == ArtifactKind.html ||
        artifact.kind == ArtifactKind.code) {
      candidate = artifact;
      break;
    }
  }
  if (candidate == null) return null;

  final lower = userInput.toLowerCase();

  // "Build me a pricing page" is a new deliverable even mid-conversation —
  // unless it also points back at what exists ("rebuild the page with…").
  if (_freshBuildSignal.hasMatch(lower) &&
      !_artifactReferenceKeywords.any(lower.contains)) {
    return null;
  }

  if (_artifactReferenceKeywords.any(lower.contains) ||
      _revisionSignal.hasMatch(lower)) {
    return candidate;
  }
  return null;
}

/// How many images a combined build request wants: an explicit count
/// ("3 photos") wins; vague plurals ("several", "photos") default to a
/// small gallery; a singular mention ("a logo") wants just one.
int photoCountHint(String input) {
  final lower = input.toLowerCase();
  final numMatch = RegExp(r'\b(\d+)\s*(photos?|images?|pictures?|logos?)\b')
      .firstMatch(lower);
  if (numMatch != null) {
    return int.parse(numMatch.group(1)!).clamp(1, 6);
  }
  if (RegExp(r'\b(several|multiple|many)\b').hasMatch(lower)) return 3;
  if (RegExp(r'\b(a few|couple)\b').hasMatch(lower)) return 2;
  if (RegExp(r'\b(photos|images|pictures|logos)\b').hasMatch(lower)) return 3;
  return 1;
}

/// Splices multiple generated images into an HTML artifact as a simple
/// responsive gallery grid, right after the opening `<body>` tag — the
/// multi-image counterpart to [embedImageAsHero] (which this delegates to
/// for a single image, so both share one insertion point).
String embedImageGallery(
  String html,
  List<Uint8List> images, {
  String altText = 'Generated image',
}) {
  if (images.length == 1) {
    return embedImageAsHero(html, images.single, altText: altText);
  }
  final safeAlt = altText.replaceAll('"', "'");
  final tiles = images
      .map((bytes) =>
          '<img src="data:image/png;base64,${base64Encode(bytes)}" '
          'alt="$safeAlt" style="width:100%;aspect-ratio:1;object-fit:cover;'
          'border-radius:12px;" />')
      .join();
  final galleryHtml = '<div style="display:grid;'
      'grid-template-columns:repeat(auto-fit, minmax(180px, 1fr));'
      'gap:16px;max-width:960px;margin:0 auto 24px;padding:0 24px;">'
      '$tiles</div>';
  final bodyMatch =
      RegExp(r'<body[^>]*>', caseSensitive: false).firstMatch(html);
  if (bodyMatch == null) return '$galleryHtml\n$html';
  final insertAt = bodyMatch.end;
  return '${html.substring(0, insertAt)}\n$galleryHtml${html.substring(insertAt)}';
}

/// Puts generated audio into [source]: at the placeholder the model was asked
/// to leave, or — when it left none — as a player at the top of the body.
///
/// Same shape as [applyGeneratedImage], and same reason for the fallback: a
/// model that ignores the instruction still ends up with the real recording on
/// the page rather than a browser speech-synthesis stand-in.
String applyGeneratedAudio(
  String source,
  Uint8List wavBytes, {
  String label = 'Audio',
}) {
  if (source.contains(generatedAudioPlaceholder)) {
    return source.replaceAll(generatedAudioPlaceholder,
        'data:audio/wav;base64,${base64Encode(wavBytes)}');
  }
  if (!RegExp(r'<body[^>]*>', caseSensitive: false).hasMatch(source)) {
    return source;
  }
  // Written here rather than reused from `studio_composition`, which already
  // imports this file — borrowing it back would make the two mutually
  // dependent for one string of markup.
  final safeLabel = label.replaceAll('<', '&lt;').replaceAll('"', "'");
  final player = '<figure style="max-width:640px;margin:0 auto 24px;'
      'padding:0 24px;text-align:center;">'
      '<figcaption style="font:600 14px system-ui;color:#6e6e73;'
      'margin-bottom:8px;">$safeLabel</figcaption>'
      '<audio controls src="data:audio/wav;base64,${base64Encode(wavBytes)}" '
      'style="width:100%;"></audio></figure>';
  final bodyMatch =
      RegExp(r'<body[^>]*>', caseSensitive: false).firstMatch(source);
  final insertAt = bodyMatch!.end;
  return '${source.substring(0, insertAt)}\n$player${source.substring(insertAt)}';
}
